theme = "ntheme"

[editor.auto-save]
focus-lost         = true
after-delay.enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable            = true
max-wrap          = 25   # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator    = ""   # set wrap-indicator to "" to hide it

[editor.cursor-shape]
normal = "bar"

[keys.normal]
p = ["paste_after", ":format"]
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all",
]

# Copy current selection up or down.
# https://github.com/helix-editor/helix/issues/3680
S-A-down = [
  "extend_to_line_bounds",
  "yank",
  "open_below",
  "normal_mode",
  "replace_with_yanked",
  "collapse_selection",
]
S-A-up = [
  "extend_to_line_bounds",
  "yank",
  "open_above",
  "normal_mode",
  "replace_with_yanked",
  "collapse_selection",
]
# Selection grows left or right.
S-A-right = "extend_next_word_start"
S-A-left  = "extend_prev_word_start"
# Searches globally after copying selection '/'
"*" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "global_search",
]

[keys.insert]
S-A-down = [
  "normal_mode",
  "extend_to_line_bounds",
  "yank",
  "open_below",
  "replace_with_yanked",
  "collapse_selection",
]
S-A-up = [
  "normal_mode",
  "extend_to_line_bounds",
  "yank",
  "open_above",
  "replace_with_yanked",
  "collapse_selection",
]
S-A-right = "extend_next_word_start"
S-A-left = "extend_prev_word_start"
